---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: websites.apps.google.com
spec:
  group: apps.google.com
  names:
    kind: Website
    listKind: WebsiteList
    plural: websites
    singular: website
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Website is the Schema for the websites API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: WebsiteSpec defines the desired state of Website
            properties:
              image:
                description: Container image to use for the website (defaults to nginx)
                type: string
              indexHTML:
                description: The HTML content that will be served at "/"
                minLength: 1
                type: string
              replicas:
                description: Number of replicas for the website deployment
                format: int32
                minimum: 1
                type: integer
              serviceType:
                description: Service type (ClusterIP, NodePort, or LoadBalancer)
                enum:
                - ClusterIP
                - NodePort
                - LoadBalancer
                type: string
            required:
            - indexHTML
            - replicas
            type: object
          status:
            description: WebsiteStatus defines the observed state of Website.
            properties:
              availableReplicas:
                description: Number of available replicas from the Deployment
                format: int32
                type: integer
              serviceName:
                description: The name of the Service created for this website
                type: string
              url:
                description: The internal URL for accessing the website
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
